version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    tty: true
    volumes:
    - ./backend:/workspace/backend
    ports:
      - "8080:8080"
    command: bash -c "go build -o /main && /main"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    tty: true
    volumes:
      - ./frontend:/workspace/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: bash -c "npm install && npm run build && npm start"

  dev-postgres:
    container_name: pgdb
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always


