version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
    - ../:/workspace
    container_name: backend-container
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../:/workspace
    container_name: frontend-container
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge